Resources:
  nodeApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      ApplicationName: mable Elastic Beanstalk Application
      Description: Cloudformation - mable test Application 
  nodeApplicationVersion:
    Type: 'AWS::ElasticBeanstalk::ApplicationVersion'
    Properties:
      ApplicationName: !Ref nodeApplication
      Description: Initial Version
      SourceBundle:
        S3Bucket: s3-alykes-mable
        S3Key: ruby-sample.zip
  nodeEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName: !Ref nodeApplication
      SolutionStackName: 64bit Amazon Linux 2 v3.1.1 running Ruby 2.7
      OptionSettings:
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: InstanceType
          Value: t1.micro
          OptionName: IamInstanceProfile
          Value: aws-elasticbeanstalk-ec2-role
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: ServiceRole
          Value: mable-svc-eb-role
      VersionLabel: !Ref nodeApplicationVersion
Outputs:
  nodeApplication:
    Description: Application Name
    Value: !Ref nodeApplication

  nodeApplicationVersion:
    Description: Application Version
    Value: !Ref nodeApplicationVersion

  nodeEnvironment:
    Description: Environment
    Value: !Ref nodeEnvironment
