AWSTemplateFormatVersion: 2010-09-09
Description: ElasticBeanstalk cloudformation template

Resources:
  nodeApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: Tick-tack Elastic Beanstalk Application-1
      Description: Cloudformation - Tick-Tack test Application

  nodeApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref nodeApplication
      Description: Initial Version
      SourceBundle:
        S3Bucket: s3-tick-tack-templates
        S3Key: netapp.zip

  nodeEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref nodeApplication
      SolutionStackName: 64bit Windows Server 2019 v2.6.3 running IIS 10.0
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t3a.medium
          OptionName: IamInstanceProfile
          Value: aws-elasticbeanstalk-ec2-role
        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: vpc-091341cb11b26a3db
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: subnet-0d0ee2ea3ac34f9e0,subnet-045211e96ad8c3e2d
        - Namespace: aws:ec2:vpc
          OptionName: ELBSubnets
          Value: subnet-03cb437e04121ed22,subnet-0a23a7cdea0690f22
        - Namespace: aws:ec2:vpc
          OptionName: ELBScheme
          Value: public
      VersionLabel: !Ref nodeApplicationVersion

Outputs:
  nodeApplication:
    Description: Application Name
    Value: !Ref nodeApplication

  nodeApplicationVersion:
    Description: Application Version
    Value: !Ref nodeApplicationVersion

  nodeEnvironment:
    Description: Environment Name
    Value: !Ref nodeEnvironment
