AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Description: AWS CloudFormation Sample Template for creating an Amazon RDS DB instance: 
Parameters:
  DBUsername:
    NoEcho: 'true'
    Description: Username for PostgreSQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password PostgreSQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow comms for postresql database
      VpcId: vpc-6f061708
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '5432'
        ToPort: '5432'
        CidrIp: 115.70.212.0/24
      - IpProtocol: tcp
        FromPort: '5432'
        ToPort: '5432'
        CidrIp: 172.31.0.0/16
  mableDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: mableRDS
      DBName: mableDB
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: 11.6
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups: 
        - !GetAtt "DBEC2SecurityGroup.GroupId"
Outputs:
  DBEC2SecurityGroup:
    Description: Security Group Creation
    Value: !Ref DBEC2SecurityGroup
  mableDB:
    Description: PostgreSQL RDS Creation
    Value: !Ref mableDB


