Resources:
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AWSElasticBeanstalkFullAccess'
      RoleName: mable-svc-eb-role
Outputs:
  RootRole:
    Description: A reference to the role created
    Value: !Ref RootRole
