AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket 
Resources:
  S3Bucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Description: Creation of s3 bucket
    Properties:
      BucketName: s3-alykes-mable
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
Outputs:
  S3Bucket:
    Description: S3 Bucket creation
    Value: !Ref S3Bucket
